name: Run GUI tests
description: Run pytest tests for the GUI on the VM
inputs:
  VM_IP:
    description: IP address of the VM
    required: true
  SSH_PRIVATE_KEY:
    description: SSH private key for the VM
    required: true
  VM_USERNAME:
    description: Username for the VM
    required: true
runs:
  using: composite
  steps:
    - name: Run GUI tests
      shell: bash
      run: |
        ssh -T -o ConnectTimeout=10 ${{ inputs.VM_USERNAME }}@${{ inputs.VM_IP }} << 'EOF'
          set -e # Exit on error
          cd ~/aperi-mech/protego-mech/gui

          echo "Setting up Python environment for GUI tests..."
          # Check if venv exists, create if not
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate

          echo "Installing GUI dependencies..."
          pip install -q --upgrade pip
          pip install -q -e .
          pip install -q pytest pytest-cov

          echo "Running GUI tests..."
          cd test
          pytest -v --cov=../gui --cov-report=term --cov-report=xml

          echo "GUI tests completed successfully"
        EOF
