name: Run material tests
description: Run material tests on the VM, inside the Docker container
inputs:
  VM_IP:
    description: IP address of the VM
    required: true
  SSH_PRIVATE_KEY:
    description: SSH private key for the VM
    required: true
  VM_USERNAME:
    description: Username for the VM
    required: true
  build-type:
    description: Build type (e.g., Release, Debug)
    required: true
  gpu:
    description: GPU build
    required: true
  with-protego:
    description: Enable Protego build
    required: true
  vm-pool:
    description: VM pool mode (uses docker run instead of docker-compose)
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Print inputs for debugging
      shell: bash
      run: |
        echo "build-type: ${{ inputs.build-type }}"
        echo "gpu: ${{ inputs.gpu }}"
        echo "with-protego: ${{ inputs.with-protego }}"
        echo "vm-pool: ${{ inputs.vm-pool }}"

    - name: Run material tests
      shell: bash
      run: |
        ssh -T -o ConnectTimeout=10 ${{ inputs.VM_USERNAME }}@${{ inputs.VM_IP }} << 'EOF'
          set -e

          # Determine build type (case-insensitive)
          build_type="Debug"
          build_type_lower=$(echo "${{ inputs.build-type }}" | tr "[:upper:]" "[:lower:]")
          if [ "$build_type_lower" == "release" ]; then
            build_type="Release"
          fi

          # Determine build path
          build_root="build"
          if [ "${{ inputs.with-protego }}" == "true" ]; then
            build_root="protego-mech/build"
          fi
          build_path="${build_root}/${build_type}"
          if [ "${{ inputs.gpu }}" == "true" ]; then
            build_path="${build_path}_gpu"
          fi

          echo "Build path: $build_path"

          if [ "${{ inputs.vm-pool }}" == "true" ]; then
            # VM Pool mode: Use docker run
            docker_image="ghcr.io/aperijake/aperi-mech:cuda-t4"
            gpu_flag=""
            if [ "${{ inputs.gpu }}" == "true" ]; then
              gpu_flag="--gpus all"
            fi

            volume_mounts="-v /mnt/builds:/tmp/aperi-builds"
            if [ "${{ inputs.with-protego }}" == "true" ]; then
              volume_mounts="$volume_mounts -v /mnt/builds/protego-builds:/tmp/protego-builds"
            fi

            docker run --rm $gpu_flag $volume_mounts \
              $docker_image /bin/bash -c '
                set -e
                cd /home/aperi-mech_docker/aperi-mech

                # Create symlinks to mounted build directories
                ln -sf /tmp/aperi-builds build
                if [ "${{ inputs.with-protego }}" == "true" ]; then
                  ln -sf /tmp/protego-builds protego-mech/build
                fi

                cd '"${build_path}"'

                echo "Setting up Spack environment..."
                source /home/aperi-mech_docker/aperi-mech/venv/bin/activate
                spack env activate aperi-mech

                echo "Running material tests..."
                make run_material_tests
              ' || { echo "Material test step failed"; exit 1; }

          else
            # Old single-VM mode: Use docker-compose
            cd ~/aperi-mech

            compose_file=docker/docker-compose.yml
            service_name=aperi-mech-development
            if [ "${{ inputs.gpu }}" == "true" ]; then
              compose_file=docker/docker-compose_nvidia.yml
              service_name=aperi-mech-gpu-development
            fi

            echo "Compose file: $compose_file"
            echo "Service name: $service_name"

            docker-compose -f $compose_file run --rm $service_name /bin/bash -c "
              build_root=~/aperi-mech_host/${build_root}
              build_path=\${build_root}/${build_type}"
              if [ "${{ inputs.gpu }}" == "true" ]; then
                build_path="\${build_path}_gpu"
              fi

              echo \"Build path: \$build_path\"
              cd \$build_path

              echo 'Setting up Spack environment...'
              source \$APERI_MECH_ROOT/venv/bin/activate
              spack env activate aperi-mech

              echo 'Running material tests...'
              make run_material_tests
            " || { echo "Material test step failed"; exit 1; }
          fi
        EOF
