name: Run performance tests on aperi-mech executable
description: Run performance tests on the VM, inside the Docker container
inputs:
  VM_IP:
    description: IP address of the VM
    required: true
  VM_USERNAME:
    description: Username for the VM
    required: true
  gpu:
    description: Run GPU tests
    required: true
  parallel:
    description: Run parallel tests
    required: true
runs:
  using: composite
  steps:
    - name: Print inputs for debugging
      shell: bash
      run: |
        echo "gpu: ${{ inputs.gpu }}"
        echo "parallel: ${{ inputs.parallel }}"

    - name: Write known_hosts file
      run: echo "${{ secrets.VM_KNOWN_HOST }}" > ~/.ssh/known_hosts

    - name: Run aperi-mech performance tests
      shell: bash
      run: python3 ./.github/actions/run-aperi-mech-performance-tests/run_aperi-mech_performance_tests.py --ip ${{ inputs.VM_IP }} --username ${{ inputs.VM_USERNAME }} --gpu ${{ inputs.gpu }} --parallel ${{ inputs.parallel }}
