name: Run performance tests on aperi-mech executable
description: Run performance tests on the VM, inside the Docker container
inputs:
  VM_IP:
    description: IP address of the VM
    required: true
  VM_USERNAME:
    description: Username for the VM
    required: true
  gpu:
    description: Run GPU tests
    required: true
  parallel:
    description: Run parallel tests
    required: true
runs:
  using: composite
  steps:
    - name: Print inputs for debugging
      shell: bash
      run: |
        echo "gpu: ${{ inputs.gpu }}"
        echo "parallel: ${{ inputs.parallel }}"

    - name: Run aperi-mech performance tests
      shell: bash
      run: ./run_performance_tests.sh ${{ inputs.VM_IP }} ${{ inputs.VM_USERNAME }} ${{ inputs.gpu }} ${{ inputs.parallel }}
