# The main purpose of this container is to run a development environment for
# the Aperi-Mech project. It is used in CI/CD pipelines and for local development.
# To start the container, run the following command:
#   docker-compose -f docker-compose.yml run --service-ports aperi-mech-development /bin/bash
# This will start the container and open a bash shell.

version: "3.8"

services:
  aperi-mech-development:
    image: aperi-mech:latest
    shm_size: 2gb # Shared memory size
    network_mode:
      host
      # build:
      #   context: .
      #   dockerfile: Dockerfile_AperiMech_Ubuntu2204
    volumes:
      - /home/azureuser/aperi-mech:/home/aperi-mech_docker/aperi-mech
      - /home/azureuser/aperifileshare1:/home/aperi-mech_docker/aperifileshare1
    working_dir: /home/aperi-mech_docker/aperi-mech
