name: Run unit tests
description: Run unit tests on the VM, inside the Docker container
inputs:
  VM_IP:
    description: IP address of the VM
    required: true
  SSH_PRIVATE_KEY:
    description: SSH private key for the VM
    required: true
  VM_USERNAME:
    description: Username for the VM
    required: true
  build-type:
    description: Build type (e.g., Release, Debug)
    required: true
  gpu:
    description: GPU build
    required: true
  num-processes:
    description: Number of processes to use for parallel unit tests
    required: true
runs:
  using: composite
  steps:
    - name: Print inputs for debugging
      shell: bash
      run: |
        echo "build-type: ${{ inputs.build-type }}"
        echo "gpu: ${{ inputs.gpu }}"
        echo "num-processes: ${{ inputs.num-processes }}"

    - name: Run unit tests
      shell: bash
      run: |
        ssh -T -o ConnectTimeout=10 ${{ inputs.VM_USERNAME }}@${{ inputs.VM_IP }} << 'EOF'
          set -e # Exit on error
          cd ~/aperi-mech

          compose_file=docker-compose.yml
          service_name=aperi-mech-development
          if [ ${{ inputs.gpu }} == 'true' ]; then
            compose_file=docker-compose_nvidia_t4_gpu.yml
            service_name=aperi-mech-gpu-development
          fi
          # Debugging
          echo "On VM, Compose file: $compose_file"
          echo "On VM, Service name: $service_name"

          docker-compose -f $compose_file run --rm $service_name /bin/bash -c '
            build_type_lower=$(echo "${{ inputs.build-type }}" | tr "[:upper:]" "[:lower:]")
            if [ "$build_type_lower" == "release" ]; then
              build_type="Release"
            fi
            build_path=~/aperi-mech/build/${{ build_type }}
            if [ ${{ inputs.gpu }} == "true" ]; then
              build_path=~/aperi-mech/build/${{ build_type }}_gpu
            fi
            # Debugging
            echo "In container, inputs.build-type: ${{ inputs.build-type }}"
            echo "In container, inputs.gpu: ${{ inputs.gpu }}"
            echo "In container, build_path: $build_path"

            cd $build_path
            echo "Setting up Spack environment..."
            . ~/spack/share/spack/setup-env.sh
            spack env activate aperi-mech

            echo "Running unit tests..."
            mpirun -n ${{ inputs.num-processes }} ./unit_tests

          '  || { echo "Unit test step failed"; exit 1; }
        EOF
