name: CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: read

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: Set up Azure CLI
              uses: azure/CLI@v1
              with:
                azcliversion: 2.62.0
                inlineScript: |
                  echo "Logging into Azure..."
                  az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
                  if [ $? -eq 0 ]; then
                    echo "Logged in successfully"
                  else
                    echo "Failed to login"
                    exit 1
                  fi
                  echo "Setting Azure subscription..."
                  az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  if [ $? -eq 0 ]; then
                      echo "Subscription set successfully"
                  else
                      echo "Failed to set subscription"
                      exit 1
                  fi
                  echo "Checking if VM is running..."
                  VM_STATUS=$(az vm get-instance-view --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_VM_NAME }} --query instanceView.statuses[1].displayStatus --output tsv)
                  if [ "$VM_STATUS" != "VM running" ]; then
                    echo "Starting VM..."
                    az vm start --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_VM_NAME }}
                    echo "::set-output name=vm_started::true"
                  else
                    echo "VM is already running"
                    echo "::set-output name=vm_started::false"
                  fi

            - name: Create .ssh directory
              run: |
                mkdir -p ~/.ssh

            - name: Add SSH key to known_hosts
              run: |
                ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

            - name: Add SSH private key
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Start SSH agent and add key
              run: |
                eval "$(ssh-agent -s)"
                ssh-add ~/.ssh/id_rsa

            - name: Build project
              run: |
                ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} "cd ~/aperi-mech && git fetch origin +refs/pull/*:refs/remotes/origin/pr/* && docker-compose run --service-ports ${{ secrets.DOCKER_SERVICE }} /bin/bash -c 'git checkout ${{ github.sha }} && ./do_configure && cd build/Release && make -j 4'"

            - name: Run tests
              run: |
                ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} "docker-compose run --service-ports ${{ secrets.DOCKER_SERVICE }} /bin/bash -c 'cd ~/aperi-mech/build/Release && make run_all_unit_tests'"

            - name: Stop Azure VM
              if: steps.start_vm.outputs.vm_started == 'true'
              run: |
                az vm deallocate --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_VM_NAME }}